# BIST Hisse Senetleri Listesi - A-K Arası
# Otomatik olarak oluşturuldu

BIST_STOCKS_AK = [
  {"symbol": "1000", "name": "YATIRIMLAR HOLDİNG"},
  {"symbol": "24", "name": "GAYRİMENKUL VE GİRİŞİM"},
          {"symbol": "A1CAP", "name": "CAPİTAL YATIRIM MENKUL"},
        {"symbol": "A1PORT", "name": "CAPİTAL PORTFÖY"},
        {"symbol": "A1YEN", "name": "A1 YENİLENEBİLİR ENERJİ"},
  {"symbol": "ACSEL", "name": "Acıselsan Acıpayam Selüloz Sanayi ve Ticaret A.Ş."},
  {"symbol": "ADANA", "name": "Adana Çimento Sanayi T.A.Ş."},
  {"symbol": "ADEL", "name": "Adel Kalemcilik Ticaret ve Sanayi A.Ş."},
  {"symbol": "ADESE", "name": "Adese Alışveriş Merkezleri Ticaret A.Ş."},
  {"symbol": "AFYON", "name": "Afyon Çimento Sanayi T.A.Ş."},
  {"symbol": "AGHOL", "name": "Ağaoğlu Gayrimenkul Yatırım Ortaklığı A.Ş."},
  {"symbol": "AGYO", "name": "Avrasya Gayrimenkul Yatırım Ortaklığı A.Ş."},
  {"symbol": "AKBNK", "name": "Akbank T.A.Ş."},
  {"symbol": "AKCNS", "name": "Akçansa Çimento Sanayi ve Ticaret A.Ş."},
  {"symbol": "AKENR", "name": "Aksa Enerji Üretim A.Ş."},
  {"symbol": "AKFGY", "name": "Akfen Gayrimenkul Yatırım Ortaklığı A.Ş."},
  {"symbol": "AKGRT", "name": "Aksigorta A.Ş."},
  {"symbol": "AKINV", "name": "Akın Tekstil A.Ş."},
  {"symbol": "AKMGY", "name": "Akmerkez Gayrimenkul Yatırım Ortaklığı A.Ş."},
  {"symbol": "AKSA", "name": "Aksa Akrilik Kimya Sanayii A.Ş."},
  {"symbol": "AKSEN", "name": "Aksa Enerji Üretim A.Ş."},
  {"symbol": "AKSGY", "name": "Akiş Gayrimenkul Yatırım Ortaklığı A.Ş."},
  {"symbol": "AKSUE", "name": "Aksu Enerji ve Ticaret A.Ş."},
  {"symbol": "AKYHO", "name": "Akdeniz Yatırım Holding A.Ş."},
  {"symbol": "ALARK", "name": "Alarko Holding A.Ş."},
  {"symbol": "ALBRK", "name": "Albaraka Türk Katılım Bankası A.Ş."},
  {"symbol": "ALCAR", "name": "Alcar Metal Sanayi ve Ticaret A.Ş."},
  {"symbol": "ALCTL", "name": "Alcatel Lucent Teletaş Telekomünikasyon A.Ş."},
  {"symbol": "ALFAS", "name": "Alfa Solar Enerji Sanayi ve Ticaret A.Ş."},
  {"symbol": "ALGYO", "name": "Alarko Gayrimenkul Yatırım Ortaklığı A.Ş."},
  {"symbol": "ALKIM", "name": "Alkim Alkali Kimya A.Ş."},
  {"symbol": "ALMAD", "name": "Altınyağ Madencilik ve Enerji Yatırımları Sanayi ve Ticaret A.Ş."},
  {"symbol": "ALNUS", "name": "Alnus Yatırım Holding A.Ş."},
  {"symbol": "ALTNY", "name": "Altınyağ Petrol Madencilik ve Enerji Yatırımları Sanayi ve Ticaret A.Ş."},
  {"symbol": "ANACM", "name": "Anadolu Cam Sanayii A.Ş."},
  {"symbol": "ANELE", "name": "Anel Elektrik Proje Taahhüt ve Ticaret A.Ş."},
  {"symbol": "ANGEN", "name": "Anadolu Hayat Emeklilik A.Ş."},
  {"symbol": "ANHYT", "name": "Anadolu Hayat Emeklilik A.Ş."},
  {"symbol": "ANSGR", "name": "Anadolu Sigorta A.Ş."},
  {"symbol": "ARCLK", "name": "Arçelik A.Ş."},
  {"symbol": "ARDYZ", "name": "Ardıyecilik Yazılım A.Ş."},
  {"symbol": "ARENA", "name": "Arena Bilgisayar Sanayi ve Ticaret A.Ş."},
  {"symbol": "ARMDA", "name": "Armada Bilgisayar Sistemleri Sanayi ve Ticaret A.Ş."},
  {"symbol": "ARZUM", "name": "Arzum Elektrikli Ev Aletleri Sanayi ve Ticaret A.Ş."},
  {"symbol": "ASELS", "name": "Aselsan Elektronik Sanayi ve Ticaret A.Ş."},
  {"symbol": "ASLAN", "name": "Aslan Çimento A.Ş."},
  {"symbol": "ASTOR", "name": "Astor Enerji A.Ş."},
  {"symbol": "ATAGY", "name": "Ata Gayrimenkul Yatırım Ortaklığı A.Ş."},
  {"symbol": "ATEKS", "name": "Ateks Tekstil A.Ş."},
  {"symbol": "ATLAS", "name": "Atlas Yatırım Holding A.Ş."},
  {"symbol": "ATSYH", "name": "Atlas Yatırım Holding A.Ş."},
  {"symbol": "AVGYO", "name": "Avrasya Gayrimenkul Yatırım Ortaklığı A.Ş."},
  {"symbol": "AVHOL", "name": "Avrasya Holding A.Ş."},
  {"symbol": "AVOD", "name": "Avod Kurutulmuş Gıda ve Tarım Ürünleri Sanayi Ticaret A.Ş."},
  {"symbol": "AVPGY", "name": "Avrupa Gayrimenkul Yatırım Ortaklığı A.Ş."},
  {"symbol": "AYCES", "name": "Ayça Çelik Konstrüksiyon Sanayi ve Ticaret A.Ş."},
  {"symbol": "AYDEM", "name": "Aydem Yenilenebilir Enerji A.Ş."},
  {"symbol": "AYEN", "name": "Ayen Enerji A.Ş."},
  {"symbol": "AYES", "name": "Aytemiz Petrolcülük A.Ş."},
  {"symbol": "AYGAZ", "name": "Aygaz A.Ş."},
  {"symbol": "AZTEK", "name": "Aztek Teknoloji Ürünleri Sanayi ve Ticaret A.Ş."},
  {"symbol": "BAGFS", "name": "Bagfaş Bandırma Gübre Fabrikaları A.Ş."},
  {"symbol": "BAKAB", "name": "Bak Ambalaj Sanayi ve Ticaret A.Ş."},
  {"symbol": "BIGCH", "name": "Büyük Şefler Gıda Turizm Tekstil Danışmanlık Organizasyon Eğitim Sanayi ve Ticaret A.Ş."},
  {"symbol": "BALAT", "name": "Balatacılar Balatacılık Sanayi ve Ticaret A.Ş."},
  {"symbol": "BANVT", "name": "Banvit Bandırma Vitaminli Yem Sanayi A.Ş."},
  {"symbol": "BARMA", "name": "Barma Mühendislik A.Ş."},
  {"symbol": "BASCM", "name": "Baştaş Başkent Çimento Sanayi ve Ticaret A.Ş."},
  {"symbol": "BASGZ", "name": "Başkent Doğalgaz Dağıtım Gayrimenkul Yatırım Ortaklığı A.Ş."},
  {"symbol": "BAYRK", "name": "Bayrak Taban Sanayi ve Ticaret A.Ş."},
  {"symbol": "BERA", "name": "Bera Holding A.Ş."},
  {"symbol": "BEYAZ", "name": "Beyaz Filo Oto Kiralama A.Ş."},
  {"symbol": "BFREN", "name": "Bosch Fren Sistemleri Sanayi ve Ticaret A.Ş."},
  {"symbol": "BHC", "name": "BHC Enerji Yatırım Holding A.Ş."},
  {"symbol": "BIMAS", "name": "BİM Birleşik Mağazalar A.Ş."},
  {"symbol": "BIZIM", "name": "Bizim Toptan Satış Mağazaları A.Ş."},
  {"symbol": "BJKAS", "name": "Beşiktaş Futbol Yatırımları Sanayi ve Ticaret A.Ş."},
  {"symbol": "BLCYT", "name": "Bilici Yatırım Sanayi ve Ticaret A.Ş."},
  {"symbol": "BNTAS", "name": "Bantaş Bandırma Ambalaj Sanayi ve Ticaret A.Ş."},
  {"symbol": "BOBET", "name": "Bodet Beton Sanayi A.Ş."},
  {"symbol": "BOSSA", "name": "Bossa Ticaret ve Sanayi İşletmeleri T.A.Ş."},
  {"symbol": "BRISA", "name": "Brisa Bridgestone Sabancı Lastik Sanayi ve Ticaret A.Ş."},
  {"symbol": "BRKO", "name": "Berkosan Yalıtım ve Tecrit Maddeleri Üretim ve Ticaret A.Ş."},
  {"symbol": "BRKSN", "name": "Birikim Varlık Yönetim A.Ş."},
  {"symbol": "BSOKE", "name": "Batısöke Çimento Sanayi T.A.Ş."},
  {"symbol": "BTCIM", "name": "Batıçim Batı Anadolu Çimento Sanayi A.Ş."},
  {"symbol": "BUCIM", "name": "Bursa Çimento Fabrikası A.Ş."},
  {"symbol": "BURCE", "name": "Burçelik A.Ş."},
  {"symbol": "BURVA", "name": "Burçelik Vana Sanayi ve Ticaret A.Ş."},
  {"symbol": "CANTE", "name": "Çan2 Termik A.Ş."},
  {"symbol": "CCOLA", "name": "Coca-Cola İçecek A.Ş."},
  {"symbol": "CELHA", "name": "Çelik Halat ve Tel Sanayii A.Ş."},
  {"symbol": "CEMAS", "name": "Çemaş Döküm Sanayi A.Ş."},
  {"symbol": "CEMTS", "name": "Çemtaş Çelik Makina Sanayi ve Ticaret A.Ş."},
  {"symbol": "CEOEM", "name": "CEO Event Medya A.Ş."},
  {"symbol": "CIMSA", "name": "Çimsa Çimento Sanayi ve Ticaret A.Ş."},
  {"symbol": "CLEBI", "name": "Çelebi Hava Servisi A.Ş."},
  {"symbol": "CUSAN", "name": "Çuhadaroğlu Metal Sanayi ve Pazarlama A.Ş."},
  {"symbol": "CVKMD", "name": "CVK Maden İşletmeleri A.Ş."},
  {"symbol": "CWENE", "name": "CW Enerji Mühendislik Ticaret ve Sanayi A.Ş."},
  {"symbol": "DCTTR", "name": "DCT Turizm ve Ticaret A.Ş."},
  {"symbol": "DAPGM", "name": "DAP Gayrimenkul Geliştirme A.Ş."},
  {"symbol": "DARDL", "name": "Dardanel Önentaş Gıda Sanayi A.Ş."},
  {"symbol": "DENGE", "name": "Denge Yatırım Holding A.Ş."},
  {"symbol": "DENIZ", "name": "Denizbank A.Ş."},
  {"symbol": "DERIM", "name": "Derimod Konfeksiyon Ayakkabı Deri Sanayi ve Ticaret A.Ş."},
  {"symbol": "DESA", "name": "Desa Deri Sanayi ve Ticaret A.Ş."},
  {"symbol": "DESPC", "name": "Despec Bilgisayar Pazarlama ve Ticaret A.Ş."},
  {"symbol": "DEVA", "name": "DEVA Holding A.Ş."},
  {"symbol": "DGATE", "name": "Datagate Bilgisayar Malzemeleri Ticaret A.Ş."},
  {"symbol": "DGGYO", "name": "Doğuş Gayrimenkul Yatırım Ortaklığı A.Ş."},
  {"symbol": "DGKLB", "name": "Doğtaş Kelebek Mobilya Sanayi ve Ticaret A.Ş."},
  {"symbol": "DIRIT", "name": "Diriteks Diriliş Tekstil Sanayi ve Ticaret A.Ş."},
  {"symbol": "DITAS", "name": "Ditaş Doğan Yedek Parça İmalat ve Teknik A.Ş."},
  {"symbol": "DMRGD", "name": "Demir Gıda Sanayi ve Ticaret A.Ş."},
  {"symbol": "DNISI", "name": "Deniz Isı Sistemleri Sanayi ve Ticaret A.Ş."},
  {"symbol": "DOAS", "name": "Doğuş Otomotiv Servis ve Ticaret A.Ş."},
  {"symbol": "DOBUR", "name": "Doğan Burda Dergi Yayıncılık ve Pazarlama A.Ş."},
  {"symbol": "DOCO", "name": "DO & CO Aktiengesellschaft"},
  {"symbol": "DOGUB", "name": "Doğusan Boru Sanayi ve Ticaret A.Ş."},
  {"symbol": "DOMINO", "name": "Domino's Pizza Türkiye"},
  {"symbol": "DURDO", "name": "Durmuşoğlu Mobilya Sanayi ve Ticaret A.Ş."},
  {"symbol": "DYOBY", "name": "DYO Boya Fabrikaları Sanayi ve Ticaret A.Ş."},
  {"symbol": "DZGYO", "name": "Deniz Gayrimenkul Yatırım Ortaklığı A.Ş."},
  {"symbol": "EBASE", "name": "Ege Profil Ticaret ve Sanayi A.Ş."},
  {"symbol": "ECILC", "name": "Eczacıbaşı İlaç Sanayi ve Ticaret A.Ş."},
  {"symbol": "ECZYT", "name": "Eczacıbaşı Yatırım Holding Ortaklığı A.Ş."},
  {"symbol": "EDATA", "name": "Edatas Enerji Dağıtım A.Ş."},
  {"symbol": "EDIP", "name": "Edip Gayrimenkul Yatırım Sanayi ve Ticaret A.Ş."},
  {"symbol": "EGCYO", "name": "Ege Gübre Sanayi A.Ş."},
  {"symbol": "EGEEN", "name": "Ege Endüstri ve Ticaret A.Ş."},
  {"symbol": "EGGUB", "name": "Ege Gübre Sanayi A.Ş."},
  {"symbol": "EGPRO", "name": "Ege Profil Ticaret ve Sanayi A.Ş."},
  {"symbol": "EGSER", "name": "Ege Seramik Sanayi ve Ticaret A.Ş."},
  {"symbol": "EKGYO", "name": "Emlak Konut Gayrimenkul Yatırım Ortaklığı A.Ş."},
  {"symbol": "EKIZ", "name": "Ekiz Yağ ve Sabun Sanayi A.Ş."},
  {"symbol": "ELITE", "name": "Elite Naturel Organik Gıda Sanayi ve Ticaret A.Ş."},
  {"symbol": "EMKEL", "name": "Emek Elektrik Endüstrisi A.Ş."},
  {"symbol": "ENJSA", "name": "Enerjisa Enerji A.Ş."},
  {"symbol": "ENKAI", "name": "Enka İnşaat ve Sanayi A.Ş."},
  {"symbol": "ENSRI", "name": "Ensari Deri Sanayi ve Ticaret A.Ş."},
  {"symbol": "ERBOS", "name": "Erbosan Erciyas Boru Sanayi ve Ticaret A.Ş."},
  {"symbol": "EREGL", "name": "Ereğli Demir ve Çelik Fabrikaları T.A.Ş."},
  {"symbol": "ERGLI", "name": "Ergül Mobilya Sanayi ve Ticaret A.Ş."},
  {"symbol": "ERSU", "name": "Ersu Meyve ve Gıda Sanayi A.Ş."},
  {"symbol": "ESCAR", "name": "Escar Filo Kiralama Hizmetleri A.Ş."},
  {"symbol": "ESCOM", "name": "Escort Teknoloji Yatırım A.Ş."},
  {"symbol": "ESEN", "name": "Esenboğa Elektrik Üretim A.Ş."},
  {"symbol": "ESK", "name": "Eskişehir Şeker Fabrikası A.Ş."},
  {"symbol": "ETILR", "name": "Etiler Gıda ve Ticaret A.Ş."},
  {"symbol": "ETYAT", "name": "Etkin Yatırım Holding A.Ş."},
  {"symbol": "EUHOL", "name": "Euro Kapital Yatırım Ortaklığı A.Ş."},
  {"symbol": "EUKYO", "name": "Euro Menkul Kıymet Yatırım Ortaklığı A.Ş."},
  {"symbol": "EUREN", "name": "Euro Trend Yatırım Ortaklığı A.Ş."},
  {"symbol": "EURSA", "name": "Euro Sigorta A.Ş."},
  {"symbol": "EYGYO", "name": "Eyüp Gayrimenkul Yatırım Ortaklığı A.Ş."},
  {"symbol": "FADE", "name": "Fade Gıda Yatırım Sanayi Ticaret A.Ş."},
  {"symbol": "FENER", "name": "Fenerbahçe Futbol A.Ş."},
  {"symbol": "FLAP", "name": "Flap Kongre Toplantı Hizmetleri Otelcilik A.Ş."},
  {"symbol": "FMIZP", "name": "F-M İzmit Piston ve Piston Segmanları Sanayi A.Ş."},
  {"symbol": "FONET", "name": "Fonet Bilgi Teknolojileri A.Ş."},
  {"symbol": "FORMT", "name": "Formet Çelik Kapı Sanayi ve Ticaret A.Ş."},
  {"symbol": "FRIGO", "name": "Frigo-Pak Gıda Maddeleri Sanayi ve Ticaret A.Ş."},
  {"symbol": "FROTO", "name": "Ford Otomotiv Sanayi A.Ş."},
  {"symbol": "FRSAN", "name": "Fersa Sanayi ve Ticaret A.Ş."},
  {"symbol": "GARAN", "name": "Türkiye Garanti Bankası A.Ş."},
  {"symbol": "GEDIK", "name": "Gedik Yatırım Menkul Değerler A.Ş."},
  {"symbol": "GEDZA", "name": "Gediz Ambalaj Sanayi ve Ticaret A.Ş."},
  {"symbol": "GENIL", "name": "Gen İlaç ve Sağlık Ürünleri Sanayi ve Ticaret A.Ş."},
  {"symbol": "GENS", "name": "Genel Sigorta A.Ş."},
  {"symbol": "GEREL", "name": "Gersan Elektrik Ticaret ve Sanayi A.Ş."},
  {"symbol": "GESAN", "name": "Girişim Elektrik Sanayi Taahhüt ve Ticaret A.Ş."},
  {"symbol": "GIPTA", "name": "Gıpta Ofis Kırtasiye ve Promosyon Ürünleri İmalat Sanayi ve Ticaret A.Ş."},
  {"symbol": "GLBMD", "name": "Global Menkul Değerler A.Ş."},
  {"symbol": "GLCVY", "name": "Gelecek Varlık Yönetimi A.Ş."},
  {"symbol": "GLRYH", "name": "Glory Holding A.Ş."},
  {"symbol": "GLYHO", "name": "Global Yatırım Holding A.Ş."},
  {"symbol": "GMTAS", "name": "Gimat Mağazacılık Ticaret A.Ş."},
  {"symbol": "GOKNR", "name": "Gökner Enerji Yatırım Holding A.Ş."},
  {"symbol": "GOLTS", "name": "Göltaş Göller Bölgesi Çimento Sanayi ve Ticaret A.Ş."},
  {"symbol": "GOODY", "name": "Goodyear Lastikleri T.A.Ş."},
  {"symbol": "GWIND", "name": "Güneş Enerji Yatırımları A.Ş."},
  {"symbol": "GORUN", "name": "Görünüm Teknoloji Sanayi ve Ticaret A.Ş."},
  {"symbol": "GRNYO", "name": "Gürtaş Tarım Enerji Yatırım Sanayi ve Ticaret A.Ş."},
  {"symbol": "GRSEL", "name": "Gürsel Turizm Taşımacılık ve Servis Ticaret A.Ş."},
  {"symbol": "GRTRK", "name": "Girişim Traktör Sanayi ve Ticaret A.Ş."},
  {"symbol": "GSDDE", "name": "GSD Denizcilik Gayrimenkul İnşaat Sanayi ve Ticaret A.Ş."},
  {"symbol": "GSDHO", "name": "GSD Holding A.Ş."},
  {"symbol": "GUBRF", "name": "Gübre Fabrikaları T.A.Ş."},
  {"symbol": "GUHEM", "name": "Güher Enerji ve Maden Sanayi A.Ş."},
  {"symbol": "GUSGR", "name": "Günes Sigorta A.Ş."},
  {"symbol": "HALKB", "name": "Türkiye Halk Bankası A.Ş."},
  {"symbol": "HATEK", "name": "Hatay Tekstil Sanayi ve Ticaret A.Ş."},
  {"symbol": "ISGSY", "name": "İş Girişim Sermayesi Yatırım Ortaklığı A.Ş."},
  {"symbol": "ISYAT", "name": "İş Yatırım Ortaklığı A.Ş."},
  {"symbol": "KUYAS", "name": "Kuyas Yatırım A.Ş."},
  {"symbol": "MRGYO", "name": "Martı Gayrimenkul Yatırım Ortaklığı A.Ş."},
  {"symbol": "MSGYO", "name": "Mistral Gayrimenkul Yatırım Ortaklığı A.Ş."},
  {"symbol": "NUGYO", "name": "Nurol Gayrimenkul Yatırım Ortaklığı A.Ş."},
  {"symbol": "OZGYO", "name": "Özderici Gayrimenkul Yatırım Ortaklığı A.Ş."},
  {"symbol": "OZKGY", "name": "Özak Gayrimenkul Yatırım Ortaklığı A.Ş."},
  {"symbol": "SINPAS", "name": "Sinpaş Gayrimenkul Yatırım Ortaklığı A.Ş."},
  {"symbol": "SNGYO", "name": "Sinpaş Gayrimenkul Yatırım Ortaklığı A.Ş."},
  {"symbol": "TEHOL", "name": "Tera Yatırım Teknoloji Holding A.Ş."},
  {"symbol": "TORUNLAR", "name": "Torunlar Gayrimenkul Yatırım Ortaklığı A.Ş."},
  {"symbol": "TRGYO", "name": "Torunlar Gayrimenkul Yatırım Ortaklığı A.Ş."},
  {"symbol": "TSGYO", "name": "TSKB Gayrimenkul Yatırım Ortaklığı A.Ş."},
  {"symbol": "VERTU", "name": "Verusatürk Girişim A.Ş."},
  {"symbol": "YGYO", "name": "Yeşil Gayrimenkul Yatırım Ortaklığı A.Ş."},
  {"symbol": "ZGOLD", "name": "Ziraat Portföy Altın Katılım ETF"},
  {"symbol": "ZPLIB", "name": "Ziraat Portföy BIST Likit Bankalar Endeks Fonu"},
  {"symbol": "ZPX30", "name": "Ziraat Portföy BIST 30 Endeks Fonu"},
  {"symbol": "HDFGS", "name": "Hedef Girişim Sermayesi Yatırım Ortaklığı A.Ş."},
  {"symbol": "HEDEF", "name": "Hedef Holding A.Ş."},
  {"symbol": "HEKTS", "name": "Hektaş Ticaret T.A.Ş."},
  {"symbol": "HILAL", "name": "Hilal Elektrik Sanayi ve Ticaret A.Ş."},
  {"symbol": "HKTAS", "name": "Hekimoğlu Konağı Turizm İnşaat Ticaret A.Ş."},
  {"symbol": "HKTM", "name": "Hektas Makine Sanayi ve Ticaret A.Ş."},
  {"symbol": "HLGYO", "name": "Halk Gayrimenkul Yatırım Ortaklığı A.Ş."},
  {"symbol": "HUBVC", "name": "Hedef Yatırım Bankası A.Ş."},
  {"symbol": "HUNER", "name": "Hun Enerji Yatırım Holding A.Ş."},
  {"symbol": "HURGZ", "name": "Hürriyet Gazetecilik ve Matbaacılık A.Ş."},
  {"symbol": "ICBCT", "name": "ICBC Turkey Bank A.Ş."},
  {"symbol": "IDEAS", "name": "İdealist Danışmanlık A.Ş."},
  {"symbol": "IDGYO", "name": "İdealist Gayrimenkul Yatırım Ortaklığı A.Ş."},
  {"symbol": "IEYHO", "name": "İhlas Ev Aletleri İmalat Sanayi ve Ticaret A.Ş."},
  {"symbol": "IHAAS", "name": "İhlas Haber Ajansı A.Ş."},
  {"symbol": "IHLAS", "name": "İhlas Holding A.Ş."},
  {"symbol": "IHEVA", "name": "İhlas Ev Aletleri Pazarlama A.Ş."},
  {"symbol": "IHGZT", "name": "İhlas Gazetecilik A.Ş."},
  {"symbol": "IHLGM", "name": "İhlas Gayrimenkul Proje Geliştirme ve Ticaret A.Ş."},
  {"symbol": "IMASM", "name": "İmaş Makina Sanayi A.Ş."},
  {"symbol": "INDES", "name": "İndeks Bilgisayar Sistemleri Mühendislik Sanayi ve Ticaret A.Ş."},
  {"symbol": "INFO", "name": "Info Yatırım Menkul Değerler A.Ş."},
  {"symbol": "INGRM", "name": "İngram Micro Bilişim Sistemleri A.Ş."},
  {"symbol": "INVEO", "name": "İnveo Yatırım Holding A.Ş."},
  {"symbol": "INVES", "name": "İnvestco Holding A.Ş."},
  {"symbol": "IPEKE", "name": "Koza Anadolu Metal Madencilik İşletmeleri A.Ş."},
  {"symbol": "ISBIR", "name": "İşbir Holding A.Ş."},
  {"symbol": "ISBTR", "name": "İş Bankası A.Ş. (TR)"},
  {"symbol": "ISCTR", "name": "Türkiye İş Bankası A.Ş."},
  {"symbol": "ISDMR", "name": "İskenderun Demir ve Çelik A.Ş."},
  {"symbol": "ISFIN", "name": "İş Finansal Kiralama A.Ş."},
  {"symbol": "ISGYO", "name": "İş Gayrimenkul Yatırım Ortaklığı A.Ş."},
  {"symbol": "ISKPL", "name": "İş Kuleleri Proje Geliştirme A.Ş."},
  {"symbol": "ISMEN", "name": "İş Yatırım Menkul Değerler A.Ş."},
  {"symbol": "ISSEN", "name": "İş Enerji Sanayi ve Ticaret A.Ş."},
  {"symbol": "IZINV", "name": "İzmir İnvest Gayrimenkul Yatırım Ortaklığı A.Ş."},
  {"symbol": "IZMDC", "name": "İzmir Demir Çelik Sanayi A.Ş."},
  {"symbol": "JANTS", "name": "Jant Sanayi ve Ticaret A.Ş."},
  {"symbol": "KAPLM", "name": "Kaplamin Ambalaj Sanayi ve Ticaret A.Ş."},
  {"symbol": "KAREL", "name": "Karel Elektronik Sanayi ve Ticaret A.Ş."},
  {"symbol": "KARSN", "name": "Karsan Otomotiv Sanayi ve Ticaret A.Ş."},
  {"symbol": "KARTN", "name": "Kartonsan Karton Sanayi ve Ticaret A.Ş."},
  {"symbol": "KATMR", "name": "Katmerciler Araç Üstü Ekipman Sanayi ve Ticaret A.Ş."},
  {"symbol": "KAYSE", "name": "Kayseri Şeker Fabrikası A.Ş."},
  {"symbol": "KBORU", "name": "Kocaer Boru Sanayi ve Ticaret A.Ş."},
  {"symbol": "KCAER", "name": "Kocaer Çelik Sanayi ve Ticaret A.Ş."},
  {"symbol": "KCHOL", "name": "Koç Holding A.Ş."},
  {"symbol": "KENT", "name": "Kent Gıda Maddeleri Sanayi ve Ticaret A.Ş."},
  {"symbol": "KERVN", "name": "Kervansaray Yatırım Holding A.Ş."},
  {"symbol": "KFEIN", "name": "Kafein Yazılım Hizmetleri Ticaret A.Ş."},
  {"symbol": "KGYO", "name": "Kiler Gayrimenkul Yatırım Ortaklığı A.Ş."},
  {"symbol": "KIMMR", "name": "Kim Marketler Zinciri Ticaret A.Ş."},
  {"symbol": "KLGYO", "name": "Kiler GYO Gayrimenkul Yatırım Ortaklığı A.Ş."},
  {"symbol": "KLMSN", "name": "Klimasan Klima Sanayi ve Ticaret A.Ş."},
  {"symbol": "KLNMA", "name": "Klimasan Klima ve Mekanik Sistemler A.Ş."},
  {"symbol": "KMPUR", "name": "Kimpur Kimya Sanayi ve Ticaret A.Ş."},
  {"symbol": "KNFRT", "name": "Konfrut Gıda Sanayi ve Ticaret A.Ş."},
  {"symbol": "KONKA", "name": "Konya Kağıt Sanayi ve Ticaret A.Ş."},
  {"symbol": "KONTR", "name": "Kontrolmatik Teknoloji Enerji ve Mühendislik A.Ş."},
  {"symbol": "KORDS", "name": "Kordsa Teknik Tekstil A.Ş."},
  {"symbol": "KOZAA", "name": "Koza Anadolu Metal Madencilik İşletmeleri A.Ş."},
  {"symbol": "KOZAL", "name": "Koza Altın İşletmeleri A.Ş."},
  {"symbol": "KRDMA", "name": "Kardemir Karabük Demir Çelik Sanayi ve Ticaret A.Ş. (A)"},
  {"symbol": "KRDMB", "name": "Kardemir Karabük Demir Çelik Sanayi ve Ticaret A.Ş. (B)"},
  {"symbol": "KRDMD", "name": "Kardemir Karabük Demir Çelik Sanayi ve Ticaret A.Ş. (D)"},
  {"symbol": "KRONT", "name": "Kron Telekomünikasyon Hizmetleri A.Ş."},
  {"symbol": "KRPLS", "name": "Karpel Enerji Sanayi ve Ticaret A.Ş."},
  {"symbol": "KRVGD", "name": "Kervan Gıda Sanayi ve Ticaret A.Ş."},
  {"symbol": "KSTUR", "name": "Kuşadası Turizm Endüstri A.Ş."},
  {"symbol": "KTSKR", "name": "Kütahya Şeker Fabrikası A.Ş."},
  {"symbol": "KUTPO", "name": "Kütahya Porselen Sanayi A.Ş."}
]

# Toplam hisse sayısı
TOTAL_STOCKS_AK = len(BIST_STOCKS_AK)

def get_stocks_by_symbol(symbol):
    """Sembol ile hisse bulma"""
    for stock in BIST_STOCKS_AK:
        if stock["symbol"] == symbol.upper():
            return stock
    return None

def get_stocks_by_name(name):
    """İsim ile hisse bulma"""
    for stock in BIST_STOCKS_AK:
        if name.upper() in stock["name"].upper():
            return stock
    return None

def search_stocks(query):
    """Hisse arama (sembol veya isim)"""
    results = []
    query = query.upper()
    for stock in BIST_STOCKS_AK:
        if query in stock["symbol"] or query in stock["name"].upper():
            results.append(stock)
    return results
