# BIST Hisse Senetleri Listesi - L-Z Arası
# Otomatik olarak oluşturuldu

BIST_STOCKS_LZ = [
  {"symbol": "LIDFA", "name": "Lider Faktoring A.Ş."},
  {"symbol": "LINK", "name": "Link Bilgisayar Sistemleri Yazılım ve Donanım Sanayi ve Ticaret A.Ş."},
  {"symbol": "LKMNH", "name": "Lokman Hekim Sağlık Hizmetleri A.Ş."},
  {"symbol": "LOGO", "name": "Logo Yazılım Sanayi ve Ticaret A.Ş."},
  {"symbol": "LUKSK", "name": "Lüks Kadife Ticaret ve Sanayi A.Ş."},
  {"symbol": "MAALT", "name": "Marmaris Altınyunus Turistik Tesisler A.Ş."},
  {"symbol": "MAGEN", "name": "Margün Enerji Üretim Sanayi ve Ticaret A.Ş."},
  {"symbol": "MAKIM", "name": "Makim Makina Teknolojileri Sanayi ve Ticaret A.Ş."},
  {"symbol": "MANAS", "name": "Manas Enerji Yönetimi Sanayi ve Ticaret A.Ş."},
  {"symbol": "MARKA", "name": "Marka Yatırım Holding A.Ş."},
  {"symbol": "MARTI", "name": "Martı Otel İşletmeleri A.Ş."},
  {"symbol": "MAVI", "name": "Mavi Giyim Sanayi ve Ticaret A.Ş."},
  {"symbol": "MEDTR", "name": "Medical Park Sağlık Hizmetleri A.Ş."},
  {"symbol": "MEGAP", "name": "Mega Polietilen Köpük Sanayi ve Ticaret A.Ş."},
  {"symbol": "MEPET", "name": "Mepet Metro Petrol ve Tesisleri Sanayi Ticaret A.Ş."},
  {"symbol": "MERIT", "name": "Merit Turizm Yatırım ve İşletme A.Ş."},
  {"symbol": "MERCN", "name": "Mercan Kimya Sanayi ve Ticaret A.Ş."},
  {"symbol": "MERKO", "name": "Merko Gıda Sanayi ve Ticaret A.Ş."},
  {"symbol": "METRO", "name": "Metro Ticari ve Mali Yatırımlar Holding A.Ş."},
  {"symbol": "METUR", "name": "Metemtur Otelcilik ve Turizm İşletmeleri A.Ş."},
  {"symbol": "MIATK", "name": "Mia Teknoloji A.Ş."},
  {"symbol": "MIPAZ", "name": "Milpa Ticari ve Sınai Ürünler Pazarlama Sanayi ve Ticaret A.Ş."},
  {"symbol": "MMCAS", "name": "MMC Sanayi ve Ticaret A.Ş."},
  {"symbol": "MNDRS", "name": "Menderes Tekstil Sanayi ve Ticaret A.Ş."},
  {"symbol": "MNDTR", "name": "Mondi Tire Kutsan Kağıt ve Ambalaj Sanayi A.Ş."},
  {"symbol": "MOBTL", "name": "Mobiltel İletişim Hizmetleri Sanayi ve Ticaret A.Ş."},
  {"symbol": "MOGAN", "name": "Mogan Enerji Yatırım Holding A.Ş."},
  {"symbol": "MPARK", "name": "MLP Sağlık Hizmetleri A.Ş."},
  {"symbol": "MRGYO", "name": "Marmara Gayrimenkul Yatırım Ortaklığı A.Ş."},
  {"symbol": "MRSHL", "name": "Marshall Boya ve Vernik Sanayi A.Ş."},
  {"symbol": "MSGYO", "name": "Mesa Mesken Sanayi ve Ticaret A.Ş."},
  {"symbol": "MTRKS", "name": "Metro Kargo Taşımacılık ve Lojistik Hizmetleri A.Ş."},
  {"symbol": "MTRYO", "name": "Metro Yatırım Ortaklığı A.Ş."},
  {"symbol": "MUBLT", "name": "Mutlu Balatacılık Sanayi ve Ticaret A.Ş."},
  {"symbol": "MZHLD", "name": "Mazhar Zorlu Holding A.Ş."},
  {"symbol": "NATEN", "name": "Naturel Enerji Üretim Sanayi ve Ticaret A.Ş."},
  {"symbol": "NATRO", "name": "Natro Yazılım A.Ş."},
  {"symbol": "NETAS", "name": "Netaş Telekomünikasyon A.Ş."},
  {"symbol": "NIBAS", "name": "Niğbaş Niğde Beton Sanayi ve Ticaret A.Ş."},
  {"symbol": "NUGYO", "name": "Nurol Gayrimenkul Yatırım Ortaklığı A.Ş."},
  {"symbol": "NUHCM", "name": "Nuh Çimento Sanayi A.Ş."},
  {"symbol": "ODAS", "name": "Odaş Elektrik Üretim Sanayi Ticaret A.Ş."},
  {"symbol": "OFYAT", "name": "Okyanus Finansal Yatırımlar A.Ş."},
  {"symbol": "OLMIP", "name": "Olmuksan International Paper Ambalaj Sanayi ve Ticaret A.Ş."},
  {"symbol": "ONCSM", "name": "Oncosem Onkolojik Sistemler Sanayi ve Ticaret A.Ş."},
  {"symbol": "ORCAY", "name": "Orçay Ordu Çay Sanayi ve Ticaret A.Ş."},
  {"symbol": "ORGE", "name": "Orge Enerji Elektrik Taahhüt A.Ş."},
  {"symbol": "ORMA", "name": "Orma Orman Mahsulleri İştirak A.Ş."},
  {"symbol": "OSMEN", "name": "Osmanlı Yatırım Menkul Değerler A.Ş."},
  {"symbol": "OSTIM", "name": "Ostim Endüstriyel Yatırımlar ve İşletme A.Ş."},
  {"symbol": "OTKAR", "name": "Otokar Otomotiv ve Savunma Sanayi A.Ş."},
  {"symbol": "OTTO", "name": "Otto Holding A.Ş."},
  {"symbol": "OYAKC", "name": "Oyak Çimento Fabrikaları A.Ş."},
  {"symbol": "OYAYO", "name": "Oyak Yatırım Ortaklığı A.Ş."},
  {"symbol": "OYLUM", "name": "Oylum Sınai Yatırımlar A.Ş."},
  {"symbol": "OZGYO", "name": "Özderici Gayrimenkul Yatırım Ortaklığı A.Ş."},
  {"symbol": "OZKGY", "name": "Özak Gayrimenkul Yatırım Ortaklığı A.Ş."},
  {"symbol": "OZSUB", "name": "Özsu Balık Üretim Sanayi ve Ticaret A.Ş."},
  {"symbol": "PAGYO", "name": "Panora Gayrimenkul Yatırım Ortaklığı A.Ş."},
  {"symbol": "PAMEL", "name": "Pamuk Elektrik Sanayi ve Ticaret A.Ş."},
  {"symbol": "PATEK", "name": "Patek Teknoloji A.Ş."},
  {"symbol": "PAPIL", "name": "Papilon Savunma Teknoloji ve Ticaret A.Ş."},
  {"symbol": "PARSN", "name": "Parsan Makina Parçaları Sanayi A.Ş."},
  {"symbol": "PCILT", "name": "Politeknik Çimento ve İnşaat Sanayi A.Ş."},
  {"symbol": "PEGYO", "name": "Pera Gayrimenkul Yatırım Ortaklığı A.Ş."},
  {"symbol": "PEHOL", "name": "Pera Holding A.Ş."},
  {"symbol": "PETKM", "name": "Petkim Petrokimya Holding A.Ş."},
  {"symbol": "PETUN", "name": "Pınar Et ve Un Sanayi A.Ş."},
  {"symbol": "PINSU", "name": "Pınar Su ve İçecek Sanayi ve Ticaret A.Ş."},
  {"symbol": "PKART", "name": "Plastikkart Akıllı Kart İletişim Sistemleri Sanayi ve Ticaret A.Ş."},
  {"symbol": "PKENT", "name": "Pınar Süt Mamulleri Sanayi A.Ş."},
  {"symbol": "PLTUR", "name": "Planet Turizm Sanayi ve Ticaret A.Ş."},
  {"symbol": "PNSUT", "name": "Pınar Süt Mamulleri Sanayi A.Ş."},
  {"symbol": "POLHO", "name": "Polisan Holding A.Ş."},
  {"symbol": "POLTK", "name": "Politeknik Metal Sanayi ve Ticaret A.Ş."},
  {"symbol": "PRDGS", "name": "Prizma Doğalgaz Sanayi ve Ticaret A.Ş."},
  {"symbol": "PRKAB", "name": "Türk Prysmian Kablo ve Sistemleri A.Ş."},
  {"symbol": "PRKME", "name": "Park Elektrik Üretim Madencilik Sanayi ve Ticaret A.Ş."},
  {"symbol": "PRZMA", "name": "Prizma Pres Makina Sanayi ve Ticaret A.Ş."},
  {"symbol": "PSGYO", "name": "Pasifik Gayrimenkul Yatırım Ortaklığı A.Ş."},
  {"symbol": "QNBFB", "name": "QNB Finansbank A.Ş."},
  {"symbol": "QNBFL", "name": "QNB Finans Finansal Kiralama A.Ş."},
  {"symbol": "RALYH", "name": "Ralı Yatırım Holding A.Ş."},
  {"symbol": "RAYSG", "name": "Ray Sigorta A.Ş."},
  {"symbol": "RNPOL", "name": "Rönesans Holding A.Ş."},
  {"symbol": "RTALB", "name": "RTA Laboratuvarları Biyolojik Ürünler İlaç ve Makine Sanayi Ticaret A.Ş."},
  {"symbol": "RUBNS", "name": "Rubenis Tekstil Sanayi Ticaret A.Ş."},
  {"symbol": "RYGYO", "name": "Reysaş Gayrimenkul Yatırım Ortaklığı A.Ş."},
  {"symbol": "RYSAS", "name": "Reysaş Lojistik Taşımacılık ve Ticaret A.Ş."},
  {"symbol": "SAFKR", "name": "Safkar Ege Soğutmacılık Sanayi ve Ticaret A.Ş."},
  {"symbol": "SAHOL", "name": "Hacı Ömer Sabancı Holding A.Ş."},
  {"symbol": "SAMAT", "name": "Samsun Makina Sanayi A.Ş."},
  {"symbol": "SAMUR", "name": "Samur Halı Sanayi ve Ticaret A.Ş."},
  {"symbol": "SANEL", "name": "Sanel Mühendislik Elektrik Taahhüt Sanayi ve Ticaret A.Ş."},
  {"symbol": "SANFM", "name": "Sanifoam Sünger Sanayi ve Ticaret A.Ş."},
  {"symbol": "SANKO", "name": "Sanko Holding A.Ş."},
  {"symbol": "SARKY", "name": "Sarkuysan Elektrolitik Bakır Sanayi ve Ticaret A.Ş."},
  {"symbol": "SASA", "name": "Sasa Polyester Sanayi A.Ş."},
  {"symbol": "SAYAS", "name": "Say Yenilenebilir Enerji Ekipmanları Sanayi ve Ticaret A.Ş."},
  {"symbol": "SDTTR", "name": "SDT Uzay ve Savunma Teknolojileri A.Ş."},
  {"symbol": "SEKUR", "name": "Sekuro Plastik Ambalaj Sanayi A.Ş."},
  {"symbol": "SELEC", "name": "Selçuk Ecza Deposu Ticaret ve Sanayi A.Ş."},
  {"symbol": "SELVA", "name": "Selva Gıda Sanayi A.Ş."},
  {"symbol": "SEYKM", "name": "Seyitler Kimya Sanayi A.Ş."},
  {"symbol": "SILVR", "name": "Silverline Endüstri ve Ticaret A.Ş."},
  {"symbol": "SİMPL", "name": "Simplex Yazılım A.Ş."},
  {"symbol": "SİNPA", "name": "Sinpaş Gayrimenkul Yatırım Ortaklığı A.Ş."},
  {"symbol": "SKBNK", "name": "Şekerbank T.A.Ş."},
  {"symbol": "SKTAS", "name": "Söktaş Tekstil Sanayi ve Ticaret A.Ş."},
  {"symbol": "SMART", "name": "Smart Güneş Enerjisi Teknolojileri Araştırma Üretim Sanayi ve Ticaret A.Ş."},
  {"symbol": "SMRTG", "name": "Smartiks Yazılım A.Ş."},
  {"symbol": "SNGYO", "name": "Sinpaş GYO A.Ş."},
  {"symbol": "SNPAM", "name": "Sanpam Tekstil Sanayi ve Ticaret A.Ş."},
  {"symbol": "SNKRN", "name": "Sanko Enerji Sanayi ve Ticaret A.Ş."},
  {"symbol": "SODA", "name": "Soda Sanayi A.Ş."},
  {"symbol": "SOKM", "name": "Şok Marketler Ticaret A.Ş."},
  {"symbol": "SONME", "name": "Sonmez Filament Sentetik İplik ve Elyaf Sanayi ve Ticaret A.Ş."},
  {"symbol": "SONTO", "name": "Sönmez Pamuklu Sanayi A.Ş."},
  {"symbol": "SOTIP", "name": "Soda Tip Enerji Üretim A.Ş."},
  {"symbol": "SRVGY", "name": "Servet Gayrimenkul Yatırım Ortaklığı A.Ş."},
  {"symbol": "SUMAS", "name": "Sumaş Suni Tahta ve Mobilya Sanayi A.Ş."},
  {"symbol": "SUNNY", "name": "Sunny Elektronik Sanayi ve Ticaret A.Ş."},
  {"symbol": "SUNTK", "name": "Sun Tekstil Sanayi ve Ticaret A.Ş."},
  {"symbol": "SUWEN", "name": "Suwen Tekstil Sanayi Pazarlama A.Ş."},
  {"symbol": "SYHOL", "name": "Soyak Holding A.Ş."},
  {"symbol": "TATGD", "name": "Tat Gıda Sanayi A.Ş."},
  {"symbol": "TAVHL", "name": "TAV Havalimanları Holding A.Ş."},
  {"symbol": "TBORG", "name": "Türk Tuborg Bira ve Malt Sanayi A.Ş."},
  {"symbol": "TCELL", "name": "Turkcell İletişim Hizmetleri A.Ş."},
  {"symbol": "TDGYO", "name": "Treda Gayrimenkul Yatırım Ortaklığı A.Ş."},
  {"symbol": "TEKTU", "name": "Tek-Art İnşaat Ticaret Turizm Sanayi ve Yatırımlar A.Ş."},
  {"symbol": "TGSAS", "name": "Taşımacılık Gayrimenkul Sanayi A.Ş."},
  {"symbol": "THYAO", "name": "Türk Hava Yolları A.O."},
  {"symbol": "TIRE", "name": "Tire Kutsan Kağıt ve Ambalaj Sanayi A.Ş."},
  {"symbol": "TKFEN", "name": "Tekfen Holding A.Ş."},
  {"symbol": "TKNSA", "name": "Teknosa İç ve Dış Ticaret A.Ş."},
  {"symbol": "TLMAN", "name": "T. Liman İşletmeleri A.Ş."},
  {"symbol": "TMPOL", "name": "Temapol Polimer Plastik ve İnşaat Sanayi Ticaret A.Ş."},
  {"symbol": "TMSN", "name": "Tümosan Motor ve Traktör Sanayi A.Ş."},
  {"symbol": "TOASO", "name": "Tofaş Türk Otomobil Fabrikası A.Ş."},
  {"symbol": "TRCAS", "name": "Turcas Petrol A.Ş."},
  {"symbol": "TRGYO", "name": "Torunlar Gayrimenkul Yatırım Ortaklığı A.Ş."},
  {"symbol": "TRILC", "name": "Turk İlaç ve Serum Sanayi A.Ş."},
  {"symbol": "TSGYO", "name": "Tsoy Gayrimenkul Yatırım Ortaklığı A.Ş."},
  {"symbol": "TSKB", "name": "Türkiye Sınai Kalkınma Bankası A.Ş."},
  {"symbol": "TSPOR", "name": "Trabzonspor Sportif Yatırım ve Futbol İşletmeciliği Ticaret A.Ş."},
  {"symbol": "TTRAK", "name": "Türk Traktör ve Ziraat Makineleri A.Ş."},
  {"symbol": "TUKAS", "name": "Tukaş Gıda Sanayi ve Ticaret A.Ş."},
  {"symbol": "TURGG", "name": "Turcas Petrol Ürünleri Ticaret A.Ş."},
  {"symbol": "TURSG", "name": "Türkiye Sigorta A.Ş."},
  {"symbol": "UFUK", "name": "Ufuk Yatırım Yönetim ve Gayrimenkul A.Ş."},
  {"symbol": "ULKER", "name": "Ülker Bisküvi Sanayi A.Ş."},
  {"symbol": "ULUUN", "name": "Ulusoy Un Sanayi ve Ticaret A.Ş."},
  {"symbol": "UNLU", "name": "Ünlü Yatırım Holding A.Ş."},
  {"symbol": "USAK", "name": "Uşak Seramik Sanayi A.Ş."},
  {"symbol": "UTPYA", "name": "Ütopya Turizm İnşaat İşletmecilik Ticaret A.Ş."},
  {"symbol": "VAKBN", "name": "Türkiye Vakıflar Bankası T.A.O."},
  {"symbol": "VAKFN", "name": "Vakıf Finansal Kiralama A.Ş."},
  {"symbol": "VAKKO", "name": "Vakko Tekstil ve Hazır Giyim Sanayi İşletmeleri A.Ş."},
  {"symbol": "VERTU", "name": "Verusaturk Girişim Sermayesi Yatırım Ortaklığı A.Ş."},
  {"symbol": "VERUS", "name": "Verusa Holding A.Ş."},
  {"symbol": "VESBE", "name": "Vestel Beyaz Eşya Sanayi ve Ticaret A.Ş."},
  {"symbol": "VESTL", "name": "Vestel Elektronik Sanayi ve Ticaret A.Ş."},
  {"symbol": "VKGYO", "name": "Vakıf Gayrimenkul Yatırım Ortaklığı A.Ş."},
  {"symbol": "VKING", "name": "Viking Kağıt ve Selüloz A.Ş."},
  {"symbol": "VOLT", "name": "Volt Elektrik Motor Sanayi ve Ticaret A.Ş."},
  {"symbol": "VUKON", "name": "Vukon Konut Gayrimenkul Yatırım Ortaklığı A.Ş."},
  {"symbol": "WORLDP", "name": "World Point Gayrimenkul Yatırım Ortaklığı A.Ş."},
  {"symbol": "YAPRK", "name": "Yaprak Süt ve Besi Çiftlikleri Sanayi ve Ticaret A.Ş."},
  {"symbol": "YATAS", "name": "Yataş Yatak ve Yorgan Sanayi ve Ticaret A.Ş."},
  {"symbol": "YAYLA", "name": "Yayla Agro Gıda Sanayi ve Ticaret A.Ş."},
  {"symbol": "YBTAS", "name": "Yibitaş Yozgat İşçi Birliği İnşaat Malzemeleri Ticaret ve Sanayi A.Ş."},
  {"symbol": "YEOTK", "name": "Yeşil Enerji Otomotiv Sanayi ve Ticaret A.Ş."},
  {"symbol": "YESIL", "name": "Yeşil Yapı Endüstrisi A.Ş."},
  {"symbol": "YGGYO", "name": "Yeşil Gayrimenkul Yatırım Ortaklığı A.Ş."},
  {"symbol": "YGYO", "name": "Yeni Gimat Gayrimenkul Yatırım Ortaklığı A.Ş."},
  {"symbol": "YKBNK", "name": "Yapı ve Kredi Bankası A.Ş."},
  {"symbol": "YKSLN", "name": "Yükselen Çelik A.Ş."},
  {"symbol": "YONGA", "name": "Yonga Mobilya Sanayi ve Ticaret A.Ş."},
  {"symbol": "YUNSA", "name": "Yünsa Yünlü Sanayi ve Ticaret A.Ş."},
  {"symbol": "YYAPI", "name": "Yeşil Yapı A.Ş."},
  {"symbol": "ZEDUR", "name": "Zedur Enerji Elektrik Üretim A.Ş."},
  {"symbol": "ZOREN", "name": "Zorlu Enerji Elektrik Üretim A.Ş."},
  {"symbol": "AGYO", "name": "Atakule Gayrimenkul Yatırım Ortaklığı A.Ş."},
  {"symbol": "AKFGY", "name": "Akfen Gayrimenkul Yatırım Ortaklığı A.Ş."},
  {"symbol": "ALGYO", "name": "Alarko Gayrimenkul Yatırım Ortaklığı A.Ş."},
  {"symbol": "ASGYO", "name": "Asce Gayrimenkul Yatırım Ortaklığı A.Ş."},
  {"symbol": "AVTUR", "name": "Avrasya Petrol ve Turizm A.Ş."},
  {"symbol": "EKGYO", "name": "Emlak Konut Gayrimenkul Yatırım Ortaklığı A.Ş."},
  {"symbol": "GLDTR", "name": "QNB Finansbank Portföy Gold ETF"},
  {"symbol": "GMSTR", "name": "QNB Finansbank Portföy Silver ETF"},
  {"symbol": "IDGYO", "name": "İdealist Gayrimenkul Yatırım Ortaklığı A.Ş."},
  {"symbol": "KRGYO", "name": "Körfez Gayrimenkul Yatırım Ortaklığı A.Ş."},
  {"symbol": "USDTR", "name": "QNB Finansbank Portföy USD Foreign ETF"}
]

# Toplam hisse sayısı
TOTAL_STOCKS_LZ = len(BIST_STOCKS_LZ)

def get_stocks_by_symbol(symbol):
    """Sembol ile hisse bulma"""
    for stock in BIST_STOCKS_LZ:
        if stock["symbol"] == symbol.upper():
            return stock
    return None

def get_stocks_by_name(name):
    """İsim ile hisse bulma"""
    for stock in BIST_STOCKS_LZ:
        if name.upper() in stock["name"].upper():
            return stock
    return None

def search_stocks(query):
    """Hisse arama (sembol veya isim)"""
    results = []
    query = query.upper()
    for stock in BIST_STOCKS_LZ:
        if query in stock["symbol"] or query in stock["name"].upper():
            results.append(stock)
    return results
